# Generated by Django 3.1.4 on 2021-01-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingcondition',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AlterField(
            model_name='matchingcondition',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is waiting'),
        ),
    ]
