# Generated by Django 3.1.4 on 2021-01-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_auto_20210109_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingcondition',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='is waiting for approval'),
        ),
        migrations.AlterField(
            model_name='matchingcondition',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is waiting for matching'),
        ),
    ]
