# Generated by Django 3.1.4 on 2021-01-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_auto_20210109_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingcondition',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='is waiting for confirmation'),
        ),
    ]
