# Generated by Django 3.1.4 on 2021-01-09 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0004_auto_20210109_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchingCondition',
            new_name='MatchingRecord',
        ),
    ]
