# Generated by Django 3.1.4 on 2021-04-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0005_auto_20210109_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='tag name')),
            ],
        ),
        migrations.RemoveField(
            model_name='matchingrecord',
            name='game_name',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='topic name')),
                ('tags', models.ManyToManyField(to='chatrooms.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='matchingrecord',
            name='topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatrooms.topic'),
        ),
    ]
