# Generated by Django 3.1.4 on 2021-04-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0006_auto_20210410_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrecord',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatrooms.topic'),
        ),
    ]
