# Generated by Django 3.1.4 on 2021-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0007_auto_20210410_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='chatrooms.Tag'),
        ),
    ]
